import React, { useState } from 'react';
import { IncidentDetail } from '../types/incident';
import { IncidentInvestigation } from '../types/investigation';
import {
  FileText,
  Copy,
  Check,
  Download,
  Printer,
  ShieldAlert,
  Clock,
  ArrowLeft,
  Sparkles,
  AlertTriangle,
  CheckCircle2,
  ExternalLink,
  Layers,
  Flame,
} from 'lucide-react';

interface FinalReportViewProps {
  incident: IncidentDetail;
  investigation: IncidentInvestigation | null;
  onBackToWorkspace: () => void;
  onSelectEvent: (eventId: string) => void;
}

export const FinalReportView: React.FC<FinalReportViewProps> = ({
  incident,
  investigation,
  onBackToWorkspace,
  onSelectEvent,
}) => {
  const [copied, setCopied] = useState(false);

  // Generate clean markdown
  const generateMarkdownReport = (): string => {
    const title = incident.title;
    const sev = incident.severity;
    const primaryCause = investigation?.primary_hypothesis || incident.primary_hypothesis;
    const confidence = investigation?.confidence ?? 92;
    const summary = investigation?.incident_summary || incident.summary;
    const durationMinutes = incident.mitigated_at
      ? Math.max(1, Math.round((new Date(incident.mitigated_at).getTime() - new Date(incident.started_at).getTime()) / 60000))
      : 45;

    let md = `# Incident Post-Mortem Report: ${title}\n\n`;
    md += `**Incident ID:** ${incident.id}\n`;
    md += `**Severity:** ${sev}\n`;
    md += `**Affected Service:** ${incident.service}\n`;
    md += `**Time Window:** ${incident.started_at} - ${incident.mitigated_at || 'Mitigated'}\n`;
    md += `**Duration:** ${durationMinutes} minutes\n`;
    md += `**Investigation Confidence:** ${confidence}%\n\n`;
    md += `---\n\n`;

    md += `## 1. Executive Summary\n${summary}\n\n`;

    md += `## 2. Root Cause Finding\n${primaryCause}\n\n`;

    if (investigation?.supporting_evidence && investigation.supporting_evidence.length > 0) {
      md += `### Supporting Evidence\n`;
      investigation.supporting_evidence.forEach((s) => {
        md += `- **[${s.event_id}]** ${s.claim} (${s.source.toUpperCase()})\n`;
      });
      md += `\n`;
    }

    if (investigation?.contradicting_evidence && investigation.contradicting_evidence.length > 0) {
      md += `### Contradicting Evidence Evaluated\n`;
      investigation.contradicting_evidence.forEach((c) => {
        md += `- **[${c.event_id}]** ${c.claim} (${c.source.toUpperCase()})\n`;
      });
      md += `\n`;
    }

    if (investigation?.missing_evidence && investigation.missing_evidence.length > 0) {
      md += `### Missing Evidence & Limitations\n`;
      investigation.missing_evidence.forEach((m) => {
        md += `- ${m}\n`;
      });
      md += `\n`;
    }

    md += `## 3. Reconstructed Timeline\n`;
    const timelineEvents = incident.evidence_events;
    timelineEvents.forEach((e) => {
      md += `- **${new Date(e.timestamp).toISOString()}** [${e.source.toUpperCase()}] ${e.title}: ${e.summary}\n`;
    });
    md += `\n`;

    md += `## 4. Remediation Recommendations\n`;
    const actions = investigation?.recommended_actions || incident.suggested_action_items.map((act) => ({
      action: act,
      type: 'immediate_mitigation' as const,
      priority: 'high' as const,
      rationale: 'Mitigation recommendation',
    }));

    actions.forEach((a, i) => {
      const actText = typeof a === 'string' ? a : a.action;
      md += `${i + 1}. ${actText}\n`;
    });

    md += `\n---\n*Generated by BlackBox Automated Telemetry Investigation Engine*\n`;
    return md;
  };

  const handleCopyMarkdown = () => {
    const md = generateMarkdownReport();
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJson = () => {
    const durationMinutes = incident.mitigated_at
      ? Math.max(1, Math.round((new Date(incident.mitigated_at).getTime() - new Date(incident.started_at).getTime()) / 60000))
      : 45;

    const payload = {
      incident_id: incident.id,
      title: incident.title,
      severity: incident.severity,
      service: incident.service,
      started_at: incident.started_at,
      duration_minutes: durationMinutes,
      investigation: investigation || {
        primary_hypothesis: incident.primary_hypothesis,
        timeline_summary: incident.timeline_summary,
      },
      evidence_events: incident.evidence_events,
      exported_at: new Date().toISOString(),
    };

    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `incident-report-${incident.id}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="mx-auto max-w-5xl px-4 sm:px-6 py-8 space-y-8">
      {/* Top action bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-zinc-800 pb-5">
        <button
          onClick={onBackToWorkspace}
          className="flex items-center gap-2 text-xs font-mono text-zinc-400 hover:text-white transition-colors self-start"
        >
          <ArrowLeft className="h-4 w-4" />
          <span>Back to Investigation Workspace</span>
        </button>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyMarkdown}
            className="flex items-center gap-1.5 rounded-lg border border-zinc-700 bg-zinc-800 hover:bg-zinc-700 px-3.5 py-2 text-xs font-mono text-zinc-200 transition-colors cursor-pointer"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
            <span>{copied ? 'Copied Markdown' : 'Copy Markdown'}</span>
          </button>

          <button
            onClick={handleDownloadJson}
            className="flex items-center gap-1.5 rounded-lg border border-zinc-700 bg-zinc-800 hover:bg-zinc-700 px-3.5 py-2 text-xs font-mono text-zinc-200 transition-colors cursor-pointer"
          >
            <Download className="h-3.5 w-3.5" />
            <span>Download JSON</span>
          </button>

          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 rounded-lg bg-emerald-500 hover:bg-emerald-400 px-3.5 py-2 text-xs font-mono font-bold text-zinc-950 transition-colors cursor-pointer"
          >
            <Printer className="h-3.5 w-3.5" />
            <span>Print Report</span>
          </button>
        </div>
      </div>

      {/* Main Clean Printable Report Card */}
      <div className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-6 sm:p-10 space-y-8 shadow-xl text-zinc-200 font-sans">
        {/* Header Title */}
        <div className="border-b border-zinc-800 pb-6 space-y-3">
          <div className="flex flex-wrap items-center gap-2 text-xs font-mono">
            <span className="rounded bg-rose-500/10 border border-rose-500/30 px-2 py-0.5 font-bold text-rose-400">
              {incident.severity} CRITICAL
            </span>
            <span className="rounded bg-zinc-800 px-2 py-0.5 text-zinc-300">
              {incident.service}
            </span>
            <span className="text-zinc-400">{incident.id}</span>
            <span className="ml-auto text-emerald-400 font-bold">
              {investigation?.confidence ?? 92}% Investigation Confidence
            </span>
          </div>

          <h1 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">
            Incident Investigation Post-Mortem Report
          </h1>

          <p className="text-sm text-zinc-300 font-medium">
            {incident.title}
          </p>

          <div className="flex flex-wrap items-center gap-4 text-xs font-mono text-zinc-400 pt-1">
            <span>Window: {new Date(incident.started_at).toUTCString()}</span>
            <span>•</span>
            <span>
              Duration:{' '}
              {incident.mitigated_at
                ? `${Math.max(1, Math.round((new Date(incident.mitigated_at).getTime() - new Date(incident.started_at).getTime()) / 60000))} minutes`
                : 'Active / Mitigated'}
            </span>
            <span>•</span>
            <span>Evidence Count: {incident.evidence_events.length} records</span>
          </div>
        </div>

        {/* Section 1: Executive Summary */}
        <div className="space-y-3">
          <h2 className="text-xs font-mono uppercase tracking-wider text-emerald-400 font-bold">
            1. Executive Summary
          </h2>
          <p className="text-sm text-zinc-300 leading-relaxed font-sans">
            {investigation?.incident_summary || incident.summary}
          </p>
        </div>

        {/* Section 2: Root Cause Conclusion */}
        <div className="rounded-xl border border-amber-500/30 bg-amber-950/20 p-5 space-y-2">
          <h2 className="text-xs font-mono uppercase tracking-wider text-amber-400 font-bold flex items-center gap-2">
            <ShieldAlert className="h-4 w-4" />
            <span>2. Primary Root Cause Finding</span>
          </h2>
          <p className="text-sm text-white font-medium leading-relaxed">
            {investigation?.primary_hypothesis || incident.primary_hypothesis}
          </p>
        </div>

        {/* Section 3: Supporting vs Contradicting Evidence */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-3">
            <h3 className="text-xs font-mono uppercase tracking-wider text-emerald-400 font-bold">
              Supporting Evidence
            </h3>
            <div className="space-y-2">
              {(investigation?.supporting_evidence && investigation.supporting_evidence.length > 0
                ? investigation.supporting_evidence
                : incident.evidence_events.filter((e) => e.is_root_cause_candidate || e.source === 'github').map((e) => ({
                    event_id: e.id,
                    claim: e.summary,
                    source: e.source,
                  }))
              ).map((item, idx) => (
                <div
                  key={idx}
                  onClick={() => onSelectEvent(item.event_id)}
                  className="rounded-lg border border-zinc-800 bg-zinc-950/60 p-3 text-xs hover:border-emerald-500/40 cursor-pointer transition-colors"
                >
                  <div className="flex items-center justify-between font-mono text-[10px] text-zinc-400 mb-1">
                    <span className="text-emerald-400 font-bold">{item.event_id}</span>
                    <span className="uppercase">{item.source}</span>
                  </div>
                  <p className="text-zinc-300">{item.claim}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="space-y-3">
            <h3 className="text-xs font-mono uppercase tracking-wider text-rose-400 font-bold">
              Contradicting Evidence Evaluated
            </h3>
            <div className="space-y-2">
              {investigation?.contradicting_evidence && investigation.contradicting_evidence.length > 0 ? (
                investigation.contradicting_evidence.map((item, idx) => (
                  <div
                    key={idx}
                    onClick={() => onSelectEvent(item.event_id)}
                    className="rounded-lg border border-zinc-800 bg-zinc-950/60 p-3 text-xs hover:border-rose-500/40 cursor-pointer transition-colors"
                  >
                    <div className="flex items-center justify-between font-mono text-[10px] text-zinc-400 mb-1">
                      <span className="text-rose-400 font-bold">{item.event_id}</span>
                      <span className="uppercase">{item.source}</span>
                    </div>
                    <p className="text-zinc-300">{item.claim}</p>
                  </div>
                ))
              ) : (
                <div className="rounded-lg border border-zinc-800/80 bg-zinc-950/40 p-4 text-xs text-zinc-400 font-mono">
                  No contradictory signals identified. Telemetry across GitHub, Sentry, and infrastructure consistently corroborated the connection pool exhaustion hypothesis.
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Section 4: Reconstructed Chronological Timeline */}
        <div className="space-y-3">
          <h2 className="text-xs font-mono uppercase tracking-wider text-zinc-400 font-bold">
            3. Chronological Sequence of Events
          </h2>
          <div className="space-y-2 border-l border-zinc-800 pl-4 ml-2">
            {incident.evidence_events.map((evt) => (
              <div
                key={evt.id}
                onClick={() => onSelectEvent(evt.id)}
                className="group relative text-xs hover:text-emerald-300 cursor-pointer transition-colors py-1"
              >
                <div className="flex items-center gap-2 font-mono text-[11px] text-zinc-400">
                  <span className="text-zinc-200">
                    {new Date(evt.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })} UTC
                  </span>
                  <span className="rounded bg-zinc-800 px-1.5 py-0.2 text-[10px] uppercase font-bold text-zinc-300">
                    {evt.source}
                  </span>
                  <span className="text-zinc-400 font-bold">{evt.id}</span>
                </div>
                <div className="text-zinc-200 font-medium mt-0.5">{evt.title}</div>
                <div className="text-zinc-400 text-[11px]">{evt.summary}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Section 5: Recommended Action Items */}
        <div className="space-y-4 pt-2">
          <h2 className="text-xs font-mono uppercase tracking-wider text-emerald-400 font-bold">
            4. Recommended Remediation Runbook
          </h2>
          <div className="space-y-2.5">
            {(investigation?.recommended_actions || incident.suggested_action_items.map((act) => ({
              action: act,
              type: 'immediate_mitigation' as const,
              priority: 'high' as const,
              rationale: 'Suggested operational runbook item',
            }))).map((item, idx) => (
              <div
                key={idx}
                className="flex items-start gap-3 rounded-lg border border-zinc-800/80 bg-zinc-950/80 p-3 text-xs"
              >
                <span className="rounded bg-emerald-500/10 border border-emerald-500/30 px-2 py-0.5 font-mono text-emerald-400 font-bold shrink-0">
                  Step {idx + 1}
                </span>
                <div className="space-y-0.5">
                  <p className="font-semibold text-white">
                    {typeof item === 'string' ? item : item.action}
                  </p>
                  {typeof item !== 'string' && item.rationale && (
                    <p className="text-zinc-400 text-[11px]">{item.rationale}</p>
                  )}
                  <span className="inline-block text-[10px] font-mono text-amber-400/90 uppercase">
                    Recommendation (Pending operational execution)
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
